export const db = [
    {
        name: 'Tyler, the Creator',
        description: 'just a nigger',
        monthListeners: 34129832,
        songs: 52,
        ticketPrice: 100,
        tour: ['Paris', 'Texas'],
    },
    {
        name: 'Tyler, the Creator',
        description: 'just a nigger',
        monthListeners: 34129832,
        songs: 52,
        ticketPrice: 100,
        tour: ['Paris', 'Texas'],
    },
    {
        name: 'Tyler, the Creator',
        description: 'just a nigger',
        monthListeners: 34129832,
        songs: 52,
        ticketPrice: 100,
        tour: ['Paris', 'Texas'],
    },
    {
        name: 'Tyler, the Creator',
        description: 'just a nigger',
        monthListeners: 34129832,
        songs: 52,
        ticketPrice: 100,
        tour: ['Paris', 'Texas'],
    },
    {
        name: 'Tyler, the Creator',
        description: 'just a nigger',
        monthListeners: 34129832,
        songs: 52,
        ticketPrice: 100,
        tour: ['Paris', 'Texas'],
    },
    {
        name: 'Tyler, the Creator',
        description: 'just a nigger',
        monthListeners: 34129832,
        songs: 52,
        ticketPrice: 100,
        tour: ['Paris', 'Texas'],
    },
    {
        name: 'Tyler, the Creator',
        description: 'just a nigger',
        monthListeners: 34129832,
        songs: 52,
        ticketPrice: 100,
        tour: ['Paris', 'Texas'],
    },
    {
        name: 'Tyler, the Creator',
        description: 'just a nigger',
        monthListeners: 34129832,
        songs: 52,
        ticketPrice: 100,
        tour: ['Paris', 'Texas'],
    },
];
